version: 2
updates:
  # Keep GitHub Actions up to date (Dependabot-native)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly" # or "daily"
      day: "monday"
      time: "07:00"
      timezone: "America/Chicago"
    open-pull-requests-limit: 10
    labels: ["deps", "github-actions"]
    commit-message:
      prefix: "deps(gh-actions)"
    reviewers:
      - "dscv103" # adjust or remove
