# @managed-by: nixos-config-generator
# Do not edit without understanding overwrite policy.
{ lib, ... }:
let
  palette = {
    base = "#1e1e2e";
    text = "#cdd6f4";
    cursor = "#cba6f7";
    selection = "#45475a";
    selection_text = "#cdd6f4";
    black = "#45475a";
    red = "#f38ba8";
    green = "#a6e3a1";
    yellow = "#f9e2af";
    blue = "#89b4fa";
    magenta = "#cba6f7";
    cyan = "#94e2d5";
    white = "#bac2de";
    bright_black = "#585b70";
    bright_red = "#f38ba8";
    bright_green = "#a6e3a1";
    bright_yellow = "#f9e2af";
    bright_blue = "#89b4fa";
    bright_magenta = "#cba6f7";
    bright_cyan = "#94e2d5";
    bright_white = "#cdd6f4";
  };

  renderPalette =
    colors:
    lib.concatStringsSep "\n" (
      lib.imap1 (idx: color: "palette = ${toString (idx - 1)}:${color}") colors
    );

  paletteList = [
    palette.black
    palette.red
    palette.green
    palette.yellow
    palette.blue
    palette.magenta
    palette.cyan
    palette.white
    palette.bright_black
    palette.bright_red
    palette.bright_green
    palette.bright_yellow
    palette.bright_blue
    palette.bright_magenta
    palette.bright_cyan
    palette.bright_white
  ];

  ghosttyConfig = ''
    window-decoration = false
    # Config generated by Ghostty Config

    shell-integration = zsh
    clipboard-read = allow
    clipboard-write = allow
    background-opacity = 0.6
    background-blur = 15
    theme = Dracula
    background = #282a36
    foreground = #f8f8f2
    selection-background = #44475a
    selection-foreground = #ffffff
    cursor-color = #f8f8f2
    cursor-text = #282a36
    palette = 0=#21222c
    palette = 1=#ff5555
    palette = 2=#50fa7b
    palette = 3=#f1fa8c
    palette = 4=#bd93f9
    palette = 5=#ff79c6
    palette = 6=#8be9fd
    palette = 7=#f8f8f2
    palette = 8=#6272a4
    palette = 9=#ff6e6e
    palette = 10=#69ff94
    palette = 11=#ffffa5
    palette = 12=#d6acff
    palette = 13=#ff92df
    palette = 14=#a4ffff
    palette = 15=#ffffff
    font-size = 14
    font-family = MonaspiceAr NF Medium
    
  '';

in
{
  xdg.configFile."ghostty/config".text = ghosttyConfig;
}
