# .github/workflows/copilot-setup-steps.yml
name: Copilot Setup Steps

on:
  workflow_dispatch:
  push:
    paths: [.github/workflows/copilot-setup-steps.yml]
  pull_request:
    paths: [.github/workflows/copilot-setup-steps.yml]

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read

    steps:
      - name: Checkout (optional; agent will checkout if you don't)
        uses: actions/checkout@v5

      # ---- Node / pnpm ------------------------------------------------------
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install Node.js (with pnpm cache)
        if: ${{ hashFiles('**/pnpm-lock.yaml') != '' }}
        uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: |
            **/pnpm-lock.yaml

      - name: Install Node.js (no cache)
        if: ${{ hashFiles('**/pnpm-lock.yaml') == '' }}
        uses: actions/setup-node@v5
        with:
          node-version: '20'

      # ---- Build local MCP if present ---------------------------------------
      - name: Build software-planning MCP
        if: ${{ hashFiles('tools/software-planning-mcp/package.json') != '' }}
        working-directory: tools/software-planning-mcp
        shell: bash
        run: |
          set -euo pipefail
          if command -v pnpm >/dev/null 2>&1; then
            pnpm install --frozen-lockfile || pnpm install
            pnpm build || pnpm run build
          else
            npm ci
            npm run build
          fi
          if [ -f build/index.js ]; then
            echo "OK: build/index.js"
          elif [ -f dist/index.js ]; then
            echo "OK: dist/index.js"
          else
            echo "ERROR: neither build/index.js nor dist/index.js exists"
            ls -R .
            exit 1
          fi

      # ---- Create launcher (repo copy) --------------------------------------
      - name: Create launcher for software-planning MCP
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p .github/mcp
          cat > .github/mcp/launch-software-planning.js <<'EOF'
          #!/usr/bin/env node
          const fs = require("fs");
          const path = require("path");
          const { spawn } = require("child_process");

          // Prefer the real workspace path if provided by GitHub Actions.
          // Fallback to path relative to this file.
          const workspace = process.env.GITHUB_WORKSPACE;
          const root = workspace ? path.resolve(workspace)
                                 : path.resolve(__dirname, "..", "..");

          const mcpDir = path.join(root, "tools", "software-planning-mcp");

          const candidates = [
            process.env.SPMCP_ENTRY,                      // optional override
            path.join(mcpDir, "build", "index.js"),
            path.join(mcpDir, "dist", "index.js"),
          ].filter(Boolean);

          const entry = candidates.find(p => p && fs.existsSync(p));
          if (!entry) {
            console.error("ERROR: software-planning MCP entrypoint not found.");
            console.error("Tried:", candidates);
            process.exit(1);
          }

          spawn(process.execPath, [entry, ...process.argv.slice(2)], { stdio: "inherit" })
            .on("exit", code => process.exit(code));
          EOF
          chmod +x .github/mcp/launch-software-planning.js

      # ---- Mirror launcher into RUNNER_TEMP for Copilot's _temp CWD ---------
      - name: Mirror launcher into $RUNNER_TEMP for Copilot
        shell: bash
        run: |
          set -euo pipefail
          echo "RUNNER_TEMP=${RUNNER_TEMP}"
          mkdir -p "${RUNNER_TEMP}/.github/mcp"
          cp -f .github/mcp/launch-software-planning.js "${RUNNER_TEMP}/.github/mcp/launch-software-planning.js"
          chmod +x "${RUNNER_TEMP}/.github/mcp/launch-software-planning.js"
          # Show where both copies live
          ls -la .github/mcp || true
          ls -la "${RUNNER_TEMP}/.github/mcp" || true

      # ---- Sanity-check both paths ------------------------------------------
      - name: Sanity check (repo path)
        shell: bash
        run: node .github/mcp/launch-software-planning.js --help || true

      - name: Sanity check (temp path Copilot uses)
        shell: bash
        run: node "${RUNNER_TEMP}/.github/mcp/launch-software-planning.js" --help || true

      # ---- Other toolchains (optional) --------------------------------------
      - name: Install uv (for uvx / mcp-nixos)
        uses: astral-sh/setup-uv@v6

      - name: Install Nix (for flake builds, eval, dev shells)
        uses: cachix/install-nix-action@v31

      - name: Preinstall mcp-ripgrep (fast code search tools)
        run: npx -y mcp-ripgrep@latest --help

      - name: Preinstall mcp-nixos wheel
        run: uvx -q mcp-nixos --help

      - name: Preinstall sequential-thinking server (optional)
        run: npm i -g @modelcontextprotocol/server-sequential-thinking

      # ---- Quick smoke checks -----------------------------------------------
      - name: Print versions
        run: |
          node -v
          npm -v
          pnpm -v
          uv --version
          nix --version || true

      - name: Nix shell smoke test (non-fatal)
        continue-on-error: true
        run: |
          nix --version
          if [ -f "flake.nix" ]; then
            nix develop -c python -V || true
          fi

      - name: Done
        run: echo "Copilot setup complete ✅"
