name: Copilot setup steps
on:
  workflow_call:

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install uv (for uvx)
        uses: astral-sh/setup-uv@v6