# .github/workflows/copilot-setup-steps.yml
name: Copilot Setup Steps

on:
  workflow_dispatch:
  push:
    paths: [.github/workflows/copilot-setup-steps.yml]
  pull_request:
    paths: [.github/workflows/copilot-setup-steps.yml]

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read

    steps:
      - name: Checkout (optional; agent will checkout if you don't)
        uses: actions/checkout@v5

      # Install pnpm FIRST so setup-node can find it for caching
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      # Now Node + enable pnpm cache
      - name: Install Node.js (for npx / MCPs / planning server)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: |
            pnpm-lock.yaml
            **/pnpm-lock.yaml

      - name: Install uv (for uvx / mcp-nixos)
        uses: astral-sh/setup-uv@v6

      - name: Install Nix (for flake builds, eval, dev shells)
        uses: cachix/install-nix-action@v27

      - name: Preinstall mcp-ripgrep (fast code search tools)
        run: npx -y mcp-ripgrep@latest --help

      - name: Preinstall mcp-nixos wheel
        run: uvx -q mcp-nixos --help

      - name: Preinstall sequential-thinking server (optional)
        run: npm i -g @modelcontextprotocol/server-sequential-thinking

      - name: Prebuild software-planning MCP (optional)
        shell: bash
        run: |
          set -e
          if [ -f "/absolute/path/to/software-planning-mcp/package.json" ]; then
            pushd /absolute/path/to/software-planning-mcp
            npm ci
            npm run build
            popd
          else
            echo "software-planning-mcp not found at absolute path (skipping build)"
          fi

      - name: Print versions
        run: |
          node -v
          npm -v
          pnpm -v
          uv --version
          nix --version || true

      - name: Nix shell smoke test (non-fatal)
        continue-on-error: true
        run: |
          nix --version
          if [ -f "flake.nix" ]; then
            nix develop -c python -V || true
          fi

      - name: Done
        run: echo "Copilot setup complete ✅"
