name: Nix CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      # Enhanced multi-level caching for better performance
      - name: Cache Nix store
        uses: actions/cache@v4
        with:
          path: |
            /nix/store
            ~/.cache/nix
          key: nix-store-${{ runner.os }}-${{ hashFiles('flake.lock', 'flake.nix') }}
          restore-keys: |
            nix-store-${{ runner.os }}-${{ hashFiles('flake.lock') }}
            nix-store-${{ runner.os }}-

      # Cache flake evaluation results for faster subsequent runs
      - name: Cache flake evaluation
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/nix/eval-cache-v*
          key: nix-eval-${{ runner.os }}-${{ hashFiles('**/*.nix') }}
          restore-keys: |
            nix-eval-${{ runner.os }}-

      # Cache formatting tools and dependencies
      - name: Cache formatter tools
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/treefmt
          key: treefmt-${{ runner.os }}-${{ hashFiles('nix/parts/fmt.nix') }}
          restore-keys: |
            treefmt-${{ runner.os }}-

      - name: Show flake metadata with timing
        run: |
          echo "::group::Flake metadata"
          time nix flake metadata
          echo "::endgroup::"

      # Parallel execution of independent checks
      - name: Run flake checks (with timing and parallel safe operations)
        run: |
          echo "::group::Flake checks"
          start_time=$(date +%s)
          nix flake check --impure --all-systems
          end_time=$(date +%s)
          duration=$((end_time - start_time))
          echo "Flake check completed in ${duration}s"
          echo "::endgroup::"

      # Enhanced formatting check with better error reporting
      - name: Check formatting (strict)
        run: |
          echo "::group::Format checking"
          nix fmt
          if [[ $(git diff --name-only) ]]; then
            echo "::error::Files need formatting:"
            git diff --name-only
            echo ""
            echo "Run 'nix fmt' locally to fix formatting issues."
            git diff --color=always
            exit 1
          fi
          echo "All files properly formatted ✅"
          echo "::endgroup::"

      # Parallel linting checks
      - name: Run linting checks
        run: |
          echo "::group::Linting checks"
          
          # Run statix and deadnix in parallel for faster feedback
          echo "Running statix (Nix linting)..."
          nix run nixpkgs#statix -- check . &
          statix_pid=$!
          
          echo "Running deadnix (dead code detection)..."
          nix run nixpkgs#deadnix -- --fail . &
          deadnix_pid=$!
          
          # Wait for both processes and capture results
          wait $statix_pid
          statix_result=$?
          wait $deadnix_pid
          deadnix_result=$?
          
          if [ $statix_result -ne 0 ]; then
            echo "::error::Statix linting failed"
            exit 1
          fi
          
          if [ $deadnix_result -ne 0 ]; then
            echo "::error::Deadnix found unused code"
            exit 1
          fi
          
          echo "All linting checks passed ✅"
          echo "::endgroup::"

      - name: Evaluate system derivation (with performance tracking)
        run: |
          echo "::group::System evaluation"
          start_time=$(date +%s)
          result=$(nix eval .#nixosConfigurations."blazar".config.system.build.toplevel.drvPath)
          end_time=$(date +%s)
          duration=$((end_time - start_time))
          echo "System evaluation completed in ${duration}s"
          echo "Derivation: $result"
          echo "::endgroup::"

      # Add cache statistics for monitoring
      - name: Cache statistics
        if: always()
        run: |
          echo "::group::Cache Statistics"
          echo "Cache usage statistics:"
          du -sh ~/.cache/nix 2>/dev/null || echo "No Nix cache found"
          du -sh ~/.cache/treefmt 2>/dev/null || echo "No treefmt cache found" 
          echo "::endgroup::"
